#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Based on pre-commit.sample
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

declare -i run_jshint=0

while IFS= read -r -d $'\0' file; do
	if [[ $file =~ \.js$ ]]; then
		run_jshint=1
    	break
    fi
done < <(git diff --cached --name-only --diff-filter=AM -z $against)

if [ $run_jshint -eq 1 ]; then
	# assumes that the script is located on PROJECT_BASE/scripts/hooks
	cd "$script_dir/../.."
	grunt --no-color jshint
fi
exit $?